CREATE TABLE PROD
(
	PROD_CD VARCHAR(50) NOT NULL,
	PROD_NM VARCHAR(200) NOT NULL,
	PROD_DVS_CD VARCHAR(50) NOT NULL,
	FAS_DVS_CD VARCHAR(50),
	BRAND_CD VARCHAR(50) NOT NULL,
	USE_YN VARCHAR(1) NOT NULL DEFAULT 'Y',
	PRIMARY KEY(PROD_CD)
);

CREATE TABLE BRAND
(
	BRAND_CD VARCHAR(50) NOT NULL,
	BRAND_NM VARCHAR(200) NOT NULL,
	USE_YN VARCHAR(1) NOT NULL DEFAULT 'Y',
	PRIMARY KEY(BRAND_CD)
);

CREATE TABLE PROD_DVS
(
	PROD_DVS_CD VARCHAR(50) NOT NULL,
	PROD_DVS_NM VARCHAR(500) NOT NULL,
	PARE_PROD_DVS_CD VARCHAR(50) NOT NULL,
	USE_YN VARCHAR(1) NOT NULL DEFAULT 'Y',
	PRIMARY KEY(PROD_DVS_CD)
);

CREATE TABLE PROD_SELL
(
	PROD_CD VARCHAR(50) NOT NULL,
	SELL_CNT BIGINT NOT NULL,
	PRIMARY KEY(PROD_CD)
);

CREATE TABLE FAS_DVS
(
	FAS_DVS_CD VARCHAR(50) NOT NULL,
	FAS_DVS_NM VARCHAR(500) NOT NULL,
	USE_YN VARCHAR(1) NOT NULL DEFAULT 'Y',
	PRIMARY KEY(FAS_DVS_CD)
);